api_platform:
    title: 'icapps ❤ PHP'
    description: 'Template project using API platform'
    version: '1.0.0'
    show_webby: false

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    patch_formats:
        json: ['application/merge-patch+json']

    swagger:
        versions: [3]

    # The list of enabled formats. The first one will be the default.
    formats:
        json:
            mime_types: ['application/json']
        jsonld:
            mime_types: ['application/ld+json']
        html:
            mime_types: ['text/html']

    # The list of enabled error formats. The first one will be the default.
    error_formats:
        json:
            mime_types: [ 'application/json' ]
        jsonproblem:
            mime_types: ['application/problem+json']
        jsonld:
            mime_types: ['application/ld+json']

    # Global resources defaults
    defaults:
        pagination_enabled: false
        pagination_client_enabled: false